"""empty message

Revision ID: 55c5ca1df85a
Revises: None
Create Date: 2016-05-24 00:05:30.223000

"""

# revision identifiers, used by Alembic.
revision = '55c5ca1df85a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'roles', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
